### ISSUE TITLE
v1.0 not updating the list

### ISSUE THREAD

**Issue by randombyt** [keilmillerjr/shuffle-module#1]
Hi, I have been using your excellent module for AM. The latest version (1.0) has a strange issue where the list remains static during scrolling but respective artwork of list items does update. If a list has five items:

1. Arcades
2. Computers
3. Consoles
4. Handhelds
5. Exit

selection stops at fifth item (at 5. Exit) but if I press down again the art work of first item (1. Arcade) appears with the item highlighted remaining at "5. Exit". Pressing start launches the item whose artwork is showing (in this case arcade) so for all practical purposes selection is at a different spot but in AM is being shown at another spot.

The settings for last version of shuffle were:

```
fe.load_module("shuffle");

// Extend the Shuffle class
class ShuffleList extends Shuffle {
	// Overwrite the select function
	function select(slot) {
		slot.font="BebasNeue Book.ttf";
		slot.align = Align.Left;
		slot.charsize = 54;
		slot.style = Style.Bold;
		slot.set_rgb ( 240, 12, 12 );
	}
	
	// Overwrite the deselect function
	function deselect(slot) {
		slot.font="BebasNeue Book.ttf";
		slot.align = Align.Left;
		slot.charsize = 54;
		slot.style = Style.Bold;
		slot.set_rgb (20 , 20, 20);
	}
}

// Create an instance of the extended class
local list = ShuffleList(5, "text", "[Title]");
	list.slots[0].set_pos(100, 400, 400, 60);
	list.slots[1].set_pos(100, 480, 400, 60);
	list.slots[2].set_pos(100, 560, 400, 60);
	list.slots[3].set_pos(100, 640, 400, 60);
	list.slots[4].set_pos(100, 720, 400, 60);
```

I updated it to latest code as provided in readme:

```
fe.load_module("shuffle");

local list = [];
	list.push(fe.add_text("Arcade", 100, 400, 400, 60));
	list.push(fe.add_text("Computer", 100, 480, 400, 60));
	list.push(fe.add_text("Console", 100, 560, 400, 60));
	list.push(fe.add_text("Handheld", 100, 640, 400, 60));
	list.push(fe.add_text("Exit", 100, 720, 400, 60));
	
// Extend the Shuffle class
class ShuffleList extends Shuffle {
function update() {
	base.update();
}
	// Overwrite the select function
	function select(slot) {
		slot.font="BebasNeue Book.ttf";
		slot.align = Align.Left;
		slot.charsize = 54;
		slot.style = Style.Bold;
		slot.set_rgb ( 240, 12, 12 );
	}
	
	// Overwrite the deselect function
	function deselect(slot) {
		slot.font="BebasNeue Book.ttf";
		slot.align = Align.Left;
		slot.charsize = 54;
		slot.style = Style.Bold;
		slot.set_rgb (20 , 20, 20);
	}
}

// Create an instance of the extended class
local list = ShuffleList(list, "text");
```

So is this intended behavior or am I doing it wrong?

(PS: BTW Thank you for these excellent modules/ plugins, It has made AM experience much better)

**Comment by keilmillerjr** [comment]
You are currently creating an array of 5 objects. Shuffle works by changing the index_offset. Shuffle is working correctly. Your objects show no change because there is no function tied to them. Add a magic function to your objects and they should be updated respectively.
